[package]
name = "hive-router-macros"
version = "0.0.1"
edition = "2021"
license = "MIT"
publish = true
description = "Derive macros used internally by the Hive Router. They carry no stability guarantees and are not meant to be depended on directly."
repository = "https://github.com/graphql-hive/router"
homepage = "https://github.com/graphql-hive/router"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }
