[package]
name = "query-planner-bin"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "query-planner"
path = "src/main.rs"

[dependencies]
query-planner = { path = "../lib/query-planner" }
graphql-parser-hive-fork = "0.5.0"
