version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    cooldown:
      default-days: 5
    groups:
      reqwest:
        patterns:
          - "reqwest"
          - "reqwest-*"
      tokio:
        patterns:
          - "tokio"
          - "tokio-*"
      http:
        patterns:
          - "http"
          - "http-*"
      ntex:
        patterns:
          - "ntex"
          - "ntex-*"
      opentelemetry:
        patterns:
          - "opentelemetry"
          - "prometheus"
          - "opentelemetry-*"
          - "opentelemetry_sdk"
          - "tracing-opentelemetry"
      tracing:
        patterns:
          - "tracing"
          - "tracing-subscriber"
      napi:
        patterns:
          - "napi"
          - "napi-*"
      serde:
        patterns:
          - "serde"
          - "serde-*"
          - "serde_json"
          - "serde_with"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/lib/node-addon"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      artifacts:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
      docker:
        patterns:
          - "docker/"
    labels:
      - "dependencies"
      - "github-actions"
      - "chore"
