version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/lib/node-addon"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
