schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION) {
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(
  graph: join__Graph
  requires: join__FieldSet
  provides: join__FieldSet
  type: String
  external: Boolean
  override: String
  usedOverridden: Boolean
) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(
  graph: join__Graph!
  interface: String!
) repeatable on OBJECT | INTERFACE

directive @join__type(
  graph: join__Graph!
  key: join__FieldSet
  extension: Boolean! = false
  resolvable: Boolean! = true
  isInterfaceObject: Boolean! = false
) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(
  graph: join__Graph!
  member: String!
) repeatable on UNION

directive @link(
  url: String
  as: String
  for: link__Purpose
  import: [link__Import]
) repeatable on SCHEMA

scalar join__FieldSet

enum join__Graph {
  OWNER @join__graph(name: "owner", url: "http://0.0.0.0:4200/owner")
  PROVIDER @join__graph(name: "provider", url: "http://0.0.0.0:4200/provider")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Holder
  @join__type(graph: OWNER)
  @join__type(graph: PROVIDER) {
  item: Item @join__field(graph: OWNER) @join__field(graph: PROVIDER, external: true)
}

type Item
  @join__type(graph: OWNER)
  @join__type(graph: PROVIDER) {
  label: String @join__field(graph: OWNER) @join__field(graph: PROVIDER, external: true)
}

type Query
  @join__type(graph: OWNER)
  @join__type(graph: PROVIDER) {
  status: String @join__field(graph: OWNER)
  holder: Holder
    @join__field(graph: PROVIDER, provides: "item { __typename label }")
}
