# yaml-language-server: $schema=../../router-config.schema.json
supergraph:
  source: file
  path: ../supergraph.graphql
traffic_shaping:
  all:
    circuit_breaker:
      enabled: false  # Disabled globally
    dedupe_enabled: false
  subgraphs:
    accounts:
      circuit_breaker:
        enabled: true
        error_threshold: 0.6
        volume_threshold: 3
        reset_timeout: 10s
    products:
      circuit_breaker:
        enabled: true
        error_threshold: 0.7
        volume_threshold: 4
        reset_timeout: 15s
