/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class QueryPlanner {
  constructor(supergraphSdl: string)
  plan(query: string, operationName?: string | undefined | null): JsonValue
}
