/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QueryPlan {
  kind: string
  node?: PlanNode
}
export declare class QueryPlanner {
  constructor(supergraphSdl: string)
  plan(query: string, operationName?: string | undefined | null): any
  planAsync(query: string, operationName?: string | undefined | null): Promise<any>
}
