[package]
name = "gateway"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
query-planner = { path = "../../lib/query-planner" }
query-plan-executor = { path = "../../lib/query-plan-executor" }

# Tokio runtime
tokio = { version = "1.38.0", features = ["full"] }

# GraphQL
graphql-parser = "0.4.1" # Using version from original file
graphql-tools = "0.4.0"  # Using version from original file

# Serialization
serde = { version = "1.0.203", features = ["derive"] }
sonic-rs = "0.5.1"

# HTTP client and caching
moka = { version = "0.12.8", features = ["future"] }

# Tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "time",
  "json",
] }
tracing-tree = "0.4.0"
tracing-chrome = "0.7.2"

# HTTP
ulid = "1.2.1"
axum = "0.8.4"
axum-extra = "0.10.1"
axum-macros = "0.5.0"
http = "1.3.1"
hyper = { version = "1.4.1", features = ["server", "http1"] }
tower-http = { version = "0.6.6", features = [
  "fs",
  "trace",
  "cors",
  "request-id",
] }

# Utils
thiserror = "2.0.12"
lazy_static = "1.5.0"
tower = "0.5.2"
async-trait = "0.1.88"
