[package]
name = "gateway"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
query-planner = { path = "../../lib/query-planner" }
executor = { path = "../../lib/executor" }
gateway-config = { path = "../../lib/gateway-config" }

tokio = { workspace = true }
futures = { workspace = true }
graphql-parser = { workspace = true }
graphql-tools = { workspace = true }
serde = { workspace = true }
sonic-rs = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
hyper = { workspace = true, features = ["server", "http1"] }
http = { workspace = true }
http-body-util = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
tower = { workspace = true }
async-trait = { workspace = true }
xxhash-rust = { workspace = true }
rand = { workspace = true }

mimalloc = { version = "0.1.47", features = ["override"] }
moka = { version = "0.12.10", features = ["future"] }
ulid = "1.2.1"
axum = "0.8.4"
axum-extra = "0.10.1"
axum-macros = "0.5.0"
tower-http = { version = "0.6.6", features = [
  "fs",
  "trace",
  "cors",
  "request-id",
] }
