[package]
name = "gateway"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
query-planner = { path = "../../lib/query-planner" }
query-plan-executor = { path = "../../lib/query-plan-executor" }
graphql-parser = "0.4.1"
graphql-tools = "0.4.0"
actix-web = "4"
serde_json = { version = "1.0.140", features = ["preserve_order"] }
reqwest = { version = "0.12", features = ["json"] }
moka = { version = "0.12", features = ["future"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
tracing-tree = "0.4.0"
