[package]
name = "gateway"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
query-planner = { path = "../../lib/query-planner" }
executor = { path = "../../lib/executor" }

mimalloc = { version = "0.1.47", features = ["override"] }

# Async runtime
compio = { version = "0.15.0", features = ["macros"] }

# GraphQL
graphql-parser = "0.4.1" # Using version from original file
graphql-tools = "0.4.0"  # Using version from original file

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
sonic-rs = "0.5.3"

# HTTP client and caching
moka = { version = "0.12.10", features = ["future"] }

# Tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "time",
  "json",
] }
tracing-tree = "0.4.0"

# HTTP
ulid = "1.2.1"
http = "1.3.1"
ntex = { version = "2", features = ["compio"] }

# Utils
thiserror = "2.0.12"
lazy_static = "1.5.0"
async-trait = "0.1.88"
rand = "0.9.2"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
