[package]
name = "gateway"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
query-planner = { path = "../../lib/query-planner" }
query-plan-executor = { path = "../../lib/query-plan-executor" }
mimalloc = { version = "0.1.47", features = ["override"] }
compio = { workspace = true }
graphql-parser = { workspace = true }
graphql-tools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sonic-rs = { workspace = true }
moka = { version = "0.12.8", features = ["future"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
http = { workspace = true }
ntex = { version = "2", features = ["compio"] }
thiserror = { workspace = true }
lazy_static = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
