name: apollo-router-updater
on:
  schedule:
    # Every 2 hours
    - cron: "0 */2 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
defaults:
  run:
    working-directory: ./apollo-router-workspace

jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1 # v1
        with:
          rust-src-dir: ./apollo-router-workspace

      - name: setup node
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version

      - name: Check for updates
        id: check
        run: |
          cd scripts/apollo-router-updater
          npm install
          npm start

      - name: Run updates
        if: steps.check.outputs.update == 'true'
        run: cargo update -p apollo-router --precise ${{ steps.check.outputs.version }}

      - name: Create Pull Request
        if: steps.check.outputs.update == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: Update apollo-router to version ${{ steps.check.outputs.version }}
          branch: apollo-router-update-${{ steps.check.outputs.version }}
          delete-branch: true
          title: ${{ steps.check.outputs.title }}
          body: |
            Automatic update of apollo-router to version ${{ steps.check.outputs.version }}.
          assignees: kamilkisiela,dotansimha
          reviewers: kamilkisiela,dotansimha
