name: benchmark

on:
  workflow_dispatch: {}

jobs:
  k6-benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      NODE_NO_WARNINGS: true
      NODE_ENV: production
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
      - name: Setup K6
        run: |
          wget https://github.com/grafana/k6/releases/download/v0.37.0/k6-v0.37.0-linux-amd64.deb
          sudo apt-get update
          sudo apt-get install ./k6-v0.37.0-linux-amd64.deb
      - name: Install
        run: cd bench && ./install.sh
      - name: Run
        run: cd bench && ./run.sh
