name: build
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  issues: read
  checks: write
  pull-requests: write
  packages: write
  id-token: write

env:
  DOCKER_IMAGE_NAME: ghcr.io/graphql-hive/router
  DOCKER_LICENSE: MIT
  DOCKER_VENDOR: theguild
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  ZIG_VERSION: 0.14.1
  BINARY_NAME: gateway

jobs:
  binary:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: linux_arm64
            rust_target: aarch64-unknown-linux-gnu
            zigbuild_target: aarch64-unknown-linux-gnu.2.28
          - name: linux_amd64
            rust_target: x86_64-unknown-linux-gnu
            zigbuild_target: x86_64-unknown-linux-gnu.2.28
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        name: checkout
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
        name: rust toolchain (${{ matrix.rust_target }})
        with:
          target: ${{ matrix.rust_target }}
          cache-key: ${{ matrix.name }}
      - run: cargo install cargo-zigbuild
        name: install zigbuild
      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f # v2
        name: setup zig
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: compile (${{ matrix.zigbuild_target }})
        run: cargo zigbuild --release --target ${{ matrix.zigbuild_target }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: upload build artifact
        with:
          name: gateway_${{ matrix.name }}
          path: target/${{ matrix.rust_target }}/release/${{ env.BINARY_NAME }}
          if-no-files-found: error
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.rust_target }}/release/${{ env.BINARY_NAME }}
          asset_name: gateway_${{ matrix.name }}
          tag: ${{ github.ref }}
  docker:
    runs-on: ubuntu-latest
    needs:
      - binary
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: setup qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: setup buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: setup docker tags
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.licenses=${{ env.DOCKER_LICENSE }}
            org.opencontainers.image.vendor=${{ env.DOCKER_VENDOR }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ github.event.release.name }},enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
            type=sha
            type=raw,value=latest,enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
      - name: download binary artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: artifacts
          pattern: gateway_*
      - name: prepare artifacts
        run: |
          mkdir -p ./target/linux/arm64
          mkdir -p ./target/linux/amd64

          mv ./artifacts/gateway_linux_arm64/gateway ./target/linux/arm64/gateway
          mv ./artifacts/gateway_linux_amd64/gateway ./target/linux/amd64/gateway
          ls -ltra ./target/linux/arm64/
          ls -ltra ./target/linux/amd64/
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        id: docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: ./docker/gateway.Dockerfile
          context: .
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: docker pr comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          header: ${{ github.workflow }}
          message: |
            🐋 This PR was built and pushed to the following [Docker images](https://github.com/graphql-hive?ecosystem=container&tab=packages&visibility=public):

            **Image Names**: `${{ env.DOCKER_IMAGE_NAME }}`

            **Platforms**: `${{ env.DOCKER_PLATFORMS }}`

            **Image Tags**: `${{ steps.meta.outputs.tags }}`

            <details>
              <summary>Docker metadata</summary>

              ```json
              ${{ steps.docker.outputs.metadata }}
              ```
            </details>
